### ISSUE TITLE
when "instance Applicative Optional", we should not use bindOptional?

### ISSUE THREAD

**Issue by ZichaoNickFox** [tonymorris/fp-course#48]
Applicative is only Functor, only have map function, doesn't have bind function?

**Comment by tonymorris** [comment]
`Applicative` does not have bind, no.

**Comment by ZichaoNickFox** [comment]
Yes, `Applicative` or `Functor` does not have `bindOptional`, so I think the follow implementation in this repo is not good. Because it used `bindOptional` which `Applicative` or `Functor` doesn't have. I think we can only use `Functor` supported functions, such as `mapOptional`.
```haskell
instance Applicative Optional where
  pure ::
    a
    -> Optional a
  pure =
    Full
  (<*>) ::
    Optional (a -> b)
    -> Optional a
    -> Optional b
  f <*> a =
    bindOptional (`mapOptional` a) f
```
link:
https://github.com/tonymorris/fp-course/blob/73a64c3d4d0df58654a1a9a0ee9d9b11c3818911/src/Course/Applicative.hs#L101
My implement as follow.
```haskell
instance Applicative Optional where
  pure ::
    a
    -> Optional a
  pure = Full
  (<*>) ::
    Optional (a -> b)
    -> Optional a
    -> Optional b
  (<*>) (Full f) o = mapOptional f o
  (<*>) Empty _ = Empty
```
I am new in Haskell and don't know this suggestion is reasonable. So if you agree, you may update implementation in this repo.

**Comment by tonymorris** [comment]
It compiles right?

**Comment by ZichaoNickFox** [comment]
Yes, and can pass optionalTest

**Comment by bmjames** [comment]
@ZichaoNickFox not every Applicative is a Monad, but every Monad is an Applicative as well, because you can derive `<*>` from `bind`. So it is absolutely fine to write Optional's `<*>` in terms of `bindOptional`. This is only saying that "Optional is both a Monad and an Applicative". It is not saying anything universal about Applicative relying on bind, which would be incorrect.

**Comment by ZichaoNickFox** [comment]
OK, May be I should not use OOP thinking here. This repo is perfect and I have learned a lot. Thanks!
